<?php

/**
 * @file
 * New Sharing Module.
 */


/**
 * Implements hook_permission().
 */
function sharemessage_permission() {
  return array(
    'view sharemessage entities' => array(
      'title' => t('View ShareMessage entities.'),
    ),
    'administer sharemessage entities' => array(
      'title' => t('Administer ShareMessage entities.'),
    ),
  );
}

/**
 * Implements hook_entity_info().
 */
function sharemessage_entity_info() {
  $entities = array(
    'sharemessage' => array(
      'module' => 'sharemessage',
      'label' => t('ShareMessage'),
      'access callback' => 'sharemessage_access',
      'entity class' => 'ShareMessage',
      'controller class' => 'ShareMessageController',
      'metadata controller class' => 'ShareMessageMetadataController',
      'fieldable' => TRUE,
      'exportable' => TRUE,
      'base table' => 'sharemessage',
      'entity keys' => array(
        'id' => 'smid',
        'label' => 'label',
        'name' => 'name',
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        ),
        'only_og_tags' => array(
          'label' => t('Only og tags'),
          'custom settings' => FALSE,
        ),
      ),
      'admin ui' => array(
        'controller class' => 'ShareMessageUIController',
        'path' => 'admin/config/services/sharemessage',
        'menu wildcard' => '%sharemessage',
      ),
      'translation' => array(
        'entity_translation' => array(
          'base path' => 'admin/config/services/sharemessage/manage/%sharemessage',
          'edit path' => 'admin/config/services/sharemessage/manage/%sharemessage',
          'path wildcard' => '%sharemessage',
        ),
      ),
    ),
  );

  return $entities;
}

/**
 * Implements hook_menu().
 */
function sharemessage_menu() {
  $items = array();
  $items['admin/config/services/sharemessage/settings'] = array(
    'title' => 'Share message Addthis settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sharemessage_addthis_settings'),
    'access arguments' => array('administer sharemessage entities'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Access callback for sharemessage.
 */
function sharemessage_access($op, $sharemessage, $account = NULL, $entity_type = NULL) {
  switch ($op) {
    case 'view':
      return user_access('view sharemessage entities', $account);
    default:
      return user_access('administer sharemessage entities', $account);
  }
}

/**
 * Implements hook_block_info().
 */
function sharemessage_block_info() {
  $sharemessages = entity_load('sharemessage', FALSE, array('block' => 1));

  $blocks = array();
  if (!empty($sharemessages)) {
    foreach ($sharemessages as $sharemessage) {
      $blocks[$sharemessage->name] = array(
        'info' => $sharemessage->label,
        'cache' => DRUPAL_NO_CACHE,
      );
    }
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sharemessage_block_view($delta = '') {
  $sharemessage = entity_load_single('sharemessage', $delta);
  $block = array();
  
  if (!$sharemessage) {
    return $block;
  }

  $block['subject'] = $sharemessage->label;
  $block['content'] = sharemessage_view($sharemessage);

  return $block;
}

/**
 * Load a ShareMessage.
 */
function sharemessage_load($smid, $reset = FALSE) {
  $sharemessage = sharemessage_load_multiple(array($smid), array(), $reset);
  return $sharemessage ? reset($sharemessage) : FALSE;
}

/**
 * Load multiple share messages based on certain conditions.
 */
function sharemessage_load_multiple($smids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('sharemessage', $smids, $conditions, $reset);
}

/**
 * Save share message.
 */
function sharemessage_save($sharemessage) {
  entity_save('sharemessage', $sharemessage);
}

/**
 * Delete single share message.
 */
function sharemessage_delete($sharemessage) {
  entity_delete('sharemessage', entity_id('sharemessage', $sharemessage));
}

/**
 * Delete multiple share messages.
 */
function sharemessage_delete_multiple($sharemessage_ids) {
  entity_delete_multiple('sharemessage', $sharemessage_ids);
}

/**
 * Share message form.
 */
function sharemessage_form($form, &$form_state, $sharemessage) {
  global $language;

  $form_state['sharemessage'] = $sharemessage;
  $smid = entity_id('sharemessage', $sharemessage);

  $form['label'] = array(
    '#type' => 'textfield',
    '#title' => t('Label'),
    '#required' => TRUE,
    '#default_value' => isset($sharemessage->label) ? $sharemessage->label : '',
    '#weight' => -3,
  );

  if (empty($smid)) {
    $form['name'] = array(
      '#type' => 'machine_name',
      '#title' => t('Machine Name'),
      '#machine_name' => array(
        'exists' => 'sharemessage_check_machine_name_if_exist',
        'source' => array('label'),
      ),
      '#required' => TRUE,
      '#weight' => -2,
    );
  }

  field_attach_form('sharemessage', $sharemessage, $form, $form_state, $language->language);

  // Settings fieldset.
  $form['override_default_settings'] = array(
    '#type' => 'checkbox',
    '#title' => t('Override default settings'),
    '#default_value' => isset($sharemessage->override_default_settings) ? $sharemessage->override_default_settings : FALSE,
    '#weight' => 101,
  );

  $form['settings'] = array(
    '#type' => 'fieldset',
    '#tree' => TRUE,
    '#weight' => 102,
    '#states' => array(
      'invisible' => array(
        ':input[name="override_default_settings"]' => array('checked' => FALSE),
      ),
    ),
  );

  $form['settings']['services'] = array(
    '#type' => 'select',
    '#title' => t('Visible services'),
    '#multiple' => TRUE,
    '#options' => sharemessage_get_addthis_services(),
    '#default_value' => !empty($sharemessage->settings['services']) ? $sharemessage->settings['services'] : variable_get('sharemessage_default_services', array()),
    '#size' => 10,
    '#states' => array(
      'invisible' => array(
        ':input[name="override_default_settings"]' => array('checked' => FALSE),
      ),
    ),
  );

  $form['settings']['additional_services'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show additional services button'),
    '#default_value' => isset($sharemessage->settings['additional_services']) ? $sharemessage->settings['additional_services'] : variable_get('sharemessage_default_additional_services', TRUE),
    '#states' => array(
      'invisible' => array(
        ':input[name="override_default_settings"]' => array('checked' => FALSE),
      ),
    ),
  );

  $form['settings']['counter'] = array(
    '#type' => 'select',
    '#title' => t('Show Addthis counter'),
    '#empty_option' => t('No'),
    '#options' => array(
      'addthis_pill_style' => t('Pill style'),
      'addthis_bubble_style' => t('Bubble style'),
    ),
    '#default_value' => isset($sharemessage->settings['counter']) ? $sharemessage->settings['counter'] : variable_get('sharemessage_default_counter', FALSE),
    '#states' => array(
      'invisible' => array(
        ':input[name="override_default_settings"]' => array('checked' => FALSE),
      ),
    ),
  );

  $form['settings']['icon_style'] = array(
    '#type' => 'radios',
    '#title' => t('Icon style'),
    '#options' => array(
      'addthis_16x16_style' => '16x16 pix',
      'addthis_32x32_style' => '32x32 pix',
    ),
    '#default_value' => isset($sharemessage->settings['icon_style']) ? $sharemessage->settings['icon_style'] : variable_get('sharemessage_default_icon_style', 'addthis_16x16_style'),
    '#states' => array(
      'invisible' => array(
        ':input[name="override_default_settings"]' => array('checked' => FALSE),
      ),
    ),
  );

  $form['block'] = array(
    '#type' => 'checkbox',
    '#title' => t('Provide a block'),
    '#default_value' => isset($sharemessage->block) ? $sharemessage->block : 0,
    '#weight' => 103,
  );

  if (variable_get('sharemessage_message_enforcement', TRUE)) {
    $form['enforce_usage'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enforce the usage of this share message on the page it points to'),
      '#description' => t('If checked, this sharemessage will be used on the page that it is referring to and override the sharemessage there.'),
      '#default_value' => isset($sharemessage->settings['enforce_usage']) ? $sharemessage->settings['enforce_usage'] : 0,
      '#weight' => 105,
    );
  }

  if (module_exists('token')) {
    $form['sharemessage_token_help'] = array(
      '#title' => t('Replacement patterns'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#description' => t('These tokens can be used in all text fields.'),
      '#weight' => 104,
    );

    $form['sharemessage_token_help']['browser'] = array(
      '#theme' => 'token_tree',
      '#token_types' => array('node', 'sharemessage'),
    );
  }

  $submit = array();
  if (!empty($form['#submit'])) {
    $submit += $form['#submit'];
  }

  $form['actions'] = array(
    '#weight' => 106,
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save share message'),
    '#submit' => $submit + array('sharemessage_form_submit'),
  );

  return $form;
}

/**
 * Returns whether a machine name already exists.
 */
function sharemessage_check_machine_name_if_exist($value) {
  return db_query_range('SELECT 1 FROM {sharemessage} WHERE name = :name', 0, 1, array(':name' => $value))->fetchField();
}

/**
 * Share message form submit.
 */
function sharemessage_form_submit($form, &$form_state) {
  if (!$form_state['values']['override_default_settings']) {
    $form_state['values']['settings'] = array();
  }

  if (variable_get('sharemessage_message_enforcement', TRUE)) {
    $form_state['values']['settings']['enforce_usage'] = $form_state['values']['enforce_usage'];
    unset($form_state['values']['enforce_usage']);
  }

  $sharemessage = $form_state['sharemessage'];

  entity_form_submit_build_entity('sharemessage', $sharemessage, $form, $form_state);
  sharemessage_save($sharemessage);

  $info = entity_get_info('sharemessage');
  $form_state['redirect'] = $info['admin ui']['path'];

  drupal_set_message(t('Message %title saved.', array('%title' => entity_label('sharemessage', $sharemessage))));
}

/**
 * Entity view callback.
 */
function sharemessage_view(ShareMessage $sharemessage) {
  return entity_view($sharemessage->entityType(), array($sharemessage), 'full', NULL, TRUE);
}

/**
 * Implements hook_sytem_settings().
 */
function sharemessage_addthis_settings($form, $form_state) {
  $form['sharemessage_addthis_profile_id'] = array(
    '#title' => t('AddThis Profile ID'),
    '#type' => 'textfield',
    '#default_value' => variable_get('sharemessage_addthis_profile_id', ''),
  );

  $form['sharemessage_default_services'] = array(
    '#title' => t('Default visible services'),
    '#type' => 'select',
    '#multiple' => TRUE,
    '#options' => sharemessage_get_addthis_services(),
    '#default_value' => variable_get('sharemessage_default_services', array()),
    '#size' => 10,
  );

  $form['sharemessage_default_additional_services'] = array(
    '#type' => 'radios',
    '#title' => t('Show additional services button'),
    '#options' => array(
      TRUE => t('Yes'),
      FALSE => t('No'),
    ),
    '#default_value' => variable_get('sharemessage_default_additional_services', TRUE),
  );

  $form['sharemessage_default_additional_services'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show additional services button'),
    '#default_value' => variable_get('sharemessage_default_additional_services', TRUE),
  );

  $form['sharemessage_default_counter'] = array(
    '#type' => 'select',
    '#title' => t('Show Addthis counter'),
    '#empty_option' => t('No'),
    '#options' => array(
      'addthis_pill_style' => t('Pill style'),
      'addthis_bubble_style' => t('Bubble style'),
    ),
    '#default_value' => variable_get('sharemessage_default_counter', FALSE),
  );

  $form['sharemessage_default_icon_style'] = array(
    '#title' => t('Default icon style'),
    '#type' => 'radios',
    '#options' => array(
      'addthis_16x16_style' => '16x16 pix',
      'addthis_32x32_style' => '32x32 pix',
    ),
    '#default_value' => variable_get('sharemessage_default_icon_style', 'addthis_16x16_style'),
  );

  $form['sharemessage_message_enforcement'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow to enforce share messages'),
    '#description' => t('This will enforce loading of a sharemessage if the ?smid argument is present in an URL. If something else on your site is using this argument, disable this this option.'),
    '#default_value' => variable_get('sharemessage_message_enforcement', TRUE),
  );

  return system_settings_form($form);
}

/**
 * Load AddThis services.
 */
function sharemessage_get_addthis_services() {
  global $language;
  $options = &drupal_static(__FUNCTION__);

  if (!isset($options)) {
    if ($cache = cache_get('sharemessage_addthis_services:' . $language->language)) {
      $options = $cache->data;
    }
    else {
      $json_services_url = variable_get('sharemessage_addthis_services', 'http://cache.addthiscdn.com/services/v1/sharing.en.json');
      $json = file_get_contents($json_services_url);
      $output = json_decode($json);
      if (!empty($output)) {
        $options = array(t('Common') => array(), t('Mail') => array(), t('Other') => array());
        foreach ($output->data as $service) {
          if (in_array($service->code, array('facebook', 'facebook_like', 'twitter', 'xing', 'linkedin', 'wordpress', 'google_plusone_share'))) {
            $options[t('Common')][$service->code] = $service->name;
          }
          elseif (in_array($service->code, array('mail', 'gmail', 'yahoomail', 'aolmail', 'email', 'mailto'))) {
            $options[t('Mail')][$service->code] = $service->name;
          }
          else {
            $options[t('Other')][$service->code] = $service->name;
          }
        }
        // Tweet is not defined?
        $options[t('Common')]['tweet'] = t('Tweet');
        // Neither is Pinterest Follow.
        $options[t('Common')]['pinterest_follow'] = t('Pinterest follow');
        cache_set('sharemessage_addthis_services:' . $language->language, $options);
      }
      else {
        cache_clear_all('sharemessage_addthis_services:' . $language->language, 'cache', TRUE);
      }
    }
  }

  return $options;
}

/**
 * Implements hook_init().
 */
function sharemessage_init() {
  if (!empty($_GET['smid']) && variable_get('sharemessage_message_enforcement', TRUE)) {
    $sharemessage = entity_load_single('sharemessage', $_GET['smid']);
    if (!empty($sharemessage)) {
      entity_view('sharemessage', array($sharemessage->identifier() => $sharemessage), 'only_og_tags');
    }
  }
}
