
sharemessage.addthis:
  type: config_object
  mapping:
    addthis_profile_id:
      type: string
      label: Addthis profile ID
    additional_services:
      type: boolean
      label: Show additional services
    counter:
      type: boolean
      label: Show counter
    icon_style:
      type: string
      label: Icon style
    message_enforcement:
      type: boolean
      label: Enforce message through URL
    local_services_definition:
      type: boolean
      label: Local services definition
    shared_video_width:
      type: integer
      label: Shared video width
    shared_video_height:
      type: integer
      label: Shared video height
    services:
      type: sequence
      label: Enabled services
      sequence:
        - type: string
          label: Service name

sharemessage.sharemessage.*:
  type: config_entity
  label: 'Share message'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    title:
      type: label
      label: 'Title'
    message_long:
      type: label
      label: 'Long message'
    message_short:
      type: label
      label: 'Short message'
    image_url:
      type: string
      label: 'Image URL'
    fallback_image:
      type: string
      label: 'Fallback image UUID'
    video_url:
      type: string
      label: 'Video URL'
    share_url:
      type: string
      label: 'Share URL'
    plugin:
      type: string
      label: 'Plugin'
    enforce_usage:
      type: boolean
      label: Enforce usage through URL
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        override_default_settings:
          type: boolean
          label: 'Override default settings'
        additional_services:
          type: boolean
          label: Show additional services
        counter:
          type: boolean
          label: Show counter
        icon_style:
          type: string
          label: Icon style
        services:
          type: sequence
          label: Enabled services
          sequence:
            - type: string
              label: Service name

block.settings.sharemessage_block:
  type: block_settings
  mapping:
    sharemessage:
      type: string
      label: Selected share message
